### PR TITLE
Editoral review issues fix

### PR DESCRIPTION
**Pull request by rachaelbradley**
Issues 188, 189, and EA editorial review

### CODE REVIEW

**Comment by rachaelbradley** [comment]
Has issues. Will rework.

**Comment by rachaelbradley** [comment]
I was unable to fix some of the issues elswhere. This will need someone with github expertise to deconflict.

**Comment by ruoxiran** [comment]
hi Rachael, it looks like you should recreate a new branch from master branch to fix issues. the branch of  "Editoral-Review-Issues-Fix" looks like comes from my publication branch which should not merge into master.

**Comment by rachaelbradley** [comment]
Reworking in new branch.

**Pull request closed without merging**
