### PR TITLE
Design doc transfer

### PR DESCRIPTION
**Pull request by SteveALee**
Design Guide update to the content originally in the Task Force Google doc. Transfered by @ruoxiran & @SteveALee

### CODE REVIEW

**Comment by SteveALee** [comment]
@lseeman @ruoxiran @rachaelbradley 
Are there any objections to this being merged now? I believe a full review has been done by Lisa with Roy when they went through it and made more changes.

We can then deal with Rachael's branches next week.

**Comment by ruoxiran** [comment]
I am OK for merging, thanks.

**Comment by rachaelbradley** [comment]
I am also ok with merging though you might want to take my current file with spelling fixes, etc. then I can pull the bigger changes from before into the final merged file.

**Comment by SteveALee** [comment]
@rachaelbradley OK, I'll review & merge that more recent branch tomorrow am. Thanks for the work.

**Comment by lseeman** [comment]
i need to merge rachaels comments and then merg

**Comment by SteveALee** [comment]
@lseeman Ok I see you've now done it  - saves me doing it :)

However, you left my last commit on the brach out for some reason?

**Comment by SteveALee** [comment]
I'm confusd as this PR was not merged.

**Pull request closed without merging**
