### PR TITLE
add Rachael and lisa's changes into new branch

### PR DESCRIPTION
**Pull request by ruoxiran**
Hi,
I put all your commits into this branch, and closed the https://github.com/w3c/coga/pull/108.
Please go ahead work on this branch or merge it. Thank you.

Preview: https://raw.githack.com/w3c/coga/changes-after-0327/content-usable/index.html

### CODE REVIEW

**Comment by SteveALee** [comment]
Thanks @ruoxiran, I will look at later today and apply my changes!

**Comment by SteveALee** [comment]
We should change the name of this PR as it now contains more than it currently suggests

There are a LOT of broken internal refs to fix (see the Respec warning top right on the page. Suggest we leave these until about to merge back

**Comment by lseeman** [comment]
thanks for the changes. i am happy to merge

**Comment by SteveALee** [comment]
woo hooo!

**Pull request merged**
